"""Add completed db column.

Revision ID: 85d4ddc0d397
Revises:
Create Date: 2020-11-08 13:33:53.852300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d4ddc0d397'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos',
                  sa.Column('completed', sa.Boolean(),
                            nullable=True, default=False))
    op.execute("UPDATE todos SET completed = false")
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
