"""Create relationship between category and question.

Revision ID: 76201e9f954d
Revises: d2218134d146
Create Date: 2020-12-16 10:02:40.821173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76201e9f954d'
down_revision = 'd2218134d146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.execute("UPDATE questions SET category_id = 1")
    op.alter_column('questions', 'category_id', nullable=False)
    op.create_foreign_key(None, 'questions', 'categories', ['category_id'], ['id'])
    op.drop_column('questions', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'category_id')
    # ### end Alembic commands ###
